<a href="https://colab.research.google.com/github/Vaelastraszz/Algorithmie/blob/master/Algorithmie_Training_Romain.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from google.colab import drive

drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


# <h1> Longest substring within a string </h1>

<h2> Romain Solution </h2>

In [0]:
import time

s = "abcabcbbd"

def longest_subs(s):
    top = 1
    break_mark = 0
    counter = 1  
    start_time = time.time()
    
    for index,letter in enumerate(s):
    
        for i in range(break_mark, index):

            if s[index]!=s[i]:
                counter = counter + 1

            else:
                break_mark = index
                break

        top = counter if counter > top else top        
        counter = 1
        
    end_time = time.time()
    print('Duration: {}'.format(end_time - start_time))
    
    return top

In [0]:
longest_subs(s)

Duration: 1.239776611328125e-05


3

<h2> Leetcode solution </h2>

In [0]:
    def lengthOfLongestSubstring(s):
        seen = {}
        start = 0
        max_len = 0
        
        start_time = time.time()
        
        #we will use the sliding window 
        for end in range(len(s)):
            if s[end] in seen:  
                start = max(start, seen[s[end]] + 1) # if that char is already in the hash table then update the start index of the sliding window
                
            seen[s[end]] = end #we will keep track of the indices in hash table  
            
            max_len = max(max_len, end-start + 1) # update the max len by the length of the sliding window 
        
        end_time = time.time()
        print('Duration: {}'.format(end_time - start_time))
            
        return max_len

In [0]:
lengthOfLongestSubstring(s)

Duration: 1.1682510375976562e-05


3

<h2>  Longest palindrome in a string </h2> 

In [0]:
def longest(s):
    
    for i in range(len(s)):
        
        for j in reversed(range(len(s))):
            
            if s[i]==s[j] :
                
                
   
    
    
    return palindrome

In [0]:
test = "coucou"

In [0]:
for i in reversed(range(len(test))):
    print (test[i])

u
o
c
u
o
c


<h2> Detect palindrome </h2>

In [0]:
import re 

def detect(s):
    
    pal = re.sub('[^a-zA-Z]+', '', s)
    j = len(pal) - 1 
    i=0
    
    while i!=j:
        
        if pal[i]!=pal[j] :
                
                return False
                break
        else:
                
            i+= 1
            j-=1
                
            return True
    
    

In [0]:
detect("bob")

True

<h2> Gradient coding </h2>

In [0]:

eta = 0.01 #learning rate
X = np.random.rand(3,6)
y = np.random.rand(3,1)
m = 100
iteration = 1000

theta = np.random.randn(6,1)


for i in range(iteration):
    
    gradients = 2/m*X.T.dot(X.dot(theta) - y)
    theta = theta - eta*gradients
    print(theta)
    
    

In [0]:
X.dot(theta)

<h2> Reversing string <h2>

In [0]:
def reverse(s):
    
    rev=""
    
    for i in reversed(range(len(s))) :
        
        rev =  rev + s[i]
    
    return rev

In [0]:
reverse("prout")

'tuorp'

<h2> fuzzbizz </h2>

In [0]:
for i in range(190):
        
    if i%3==0 and i%5==0 :
        
        print("fuzzbizz")
        
    elif  i%5==0:
        
        print ("bizz")
        
    
    elif i%3==0 :
        
        print ("fuzz")
    
    else :
        
        print(i)

<h2> Square root computing </h2>

In [0]:
def squared(v):
    
    sqr = 0
    i = 0
    
    if v > 0:
        while i <= v:

            if int(i*i) == v:
                sqr = i              
                break

            i += 0.0001
        
        return int(sqr)  
    
    else :
        return print("not possible on negative value or null values")
       

In [0]:
squared(900)

30

<h2> Return two sum <h2>

In [0]:
def twosum(tab, target):
    
    index = np.zeros(2)
    stop = 0
    
    for i in range(tab.shape[0]):
        
        if stop ==0 :
            for j in range(i+1,tab.shape[0]) :

                if tab[j]==target - tab[i] :

                    index[0] = i
                    index[1] = j
                    stop +=1
                    break               
               
                    
        else:
            return index
            break
                

In [0]:
test = np.array([2,8,9,10,100])

In [0]:
twosum(test, 102)

array([0., 4.])

<h2> Bubble sort </h2>

In [0]:
def b_sort(tab):
    
    temp = 0 
    
    for i in range(tab.shape[0]):
        
        if i <= (tab.shape[0] - 2):
        
            j = i+1

            if tab[i] > tab[j]:

                tab[i],tab[j]= tab[j],tab[i]

    
    for i in reversed(range(tab.shape[0])):
    
            if i >= 1:
        
                j = i-1

                if tab[i] < tab[j]:

                    tab[i],tab[j]= tab[j],tab[i]


    
    return tab

In [0]:
test = np.array([2,1,5,0,3,10,4,19,8,14])

In [0]:
b_sort(test)

array([ 0,  1,  2,  3,  4,  5,  8, 10, 14, 19])

<h2> Creation d'une pile </h2>

In [0]:
class Stack:
    
    def __init__(self):
         self.items = []
            
    def push(self,item):
        return self.items.append(item)
    
    def isEmpty(self):
        return self.items == []
    
    def pop(self):
        return self.items.pop()
    
    def peek(self):
        return self.items[len(self.items)-1]
    
    def size(self):
        return len(self.items)

In [0]:
stack = Stack()

In [0]:
stack.push("prout")

In [0]:
stack.peek()

'prout'

<h2> Création d'une file </h2>

In [0]:
class Queue:
    
    def __init__(self):
         self.items = []
            
    def enqueue(self,item):
        return self.items.insert(0,item)
    
    def isEmpty(self):
        return self.items == []
    
    def dequeue(self):
        return self.items.pop()
    
    def size(self):
        return len(self.items)

In [0]:
queue= Queue()

In [0]:
queue.enqueue(4)

In [0]:
queue.enqueue(8)

In [0]:
queue.size()

1

In [0]:
queue.dequeue()

In [0]:
def HotPotato(n, num):
    
    names = n
    Q = Queue()
    
    for i in range(len(names)):
        
        Q.enqueue(names[i])
    
    while  Q.size > 1 :
        
        i = 0
        
        while i <= num :

            if i < num :
                elem = Q.dequeue()
                Q.enqueue(elem)
                i+=1

            else :

                Q.dequeue()
                break

            
    

In [0]:
names = ["jean","jacques","louis","paul","romain","alex"]

In [0]:
HotPotato(names,15)

<h2> Création d'une dequeue </h2>

In [0]:
class Dequeue:
    
    def __init__(self):
        self.items = []
            
    def addRear(self,item):
        return self.items.insert(0,item)
    
    def addFront(self,item):
        return self.items.append(item)
    
    def isEmpty(self):
        return self.items == []
    
    def removeFront(self):
        return self.items.pop()
    
    def removeRear(self):
        return self.items.pop(0)
    
    def size(self):
        return len(self.items)

<h2> Creation suite de fibonacci </h2>

<h3> Queue </h3>

In [0]:
def fibonnacci(iteration):
    
    tab = np.zeros(iteration)
    tab[0] = 1
    
    q = Queue()
    
    q.enqueue(0)
    q.enqueue(1)
    
    for i in range(iteration) :
        
        if i>=1 :
            
            elem1 = q.dequeue()
            elem2 = q.dequeue()
            tab[i]= elem1 + elem2
            q.enqueue(elem2)
            q.enqueue(tab[i])
            
    return tab
            
       

In [0]:
fibonnacci(10)

array([ 1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.])

<h3> Fibonacci  recursive</h3>

In [0]:
def recfib(n):
    
    if n<=1 :
        return n
    else:
        return recfib(n-1) + recfib(n-2)

In [0]:
print(recfib(10))

55


<h3> DProgramming fibonacci </h3>

In [0]:
storage =  {}

def fibo(n):
    if n not in storage :
        if n<=1 :
            return n
        else :
            f = fibo(n-1) + fibo(n-2)
            storage[n] = f
            return f
    else :
         return storage[n]

In [0]:
storage

{2: 1, 3: 2, 4: 3, 5: 5, 6: 8, 7: 13, 8: 21, 9: 34, 10: 55}

<h2> Climbing stairs </h2>

In [0]:
def fib(n):
    
    if n <= 1:
        return n
    else:
        return fib(n-1) + fib(n-2)
    
def countways(s):
    return fib(s+1)

In [0]:
countways(4)

5

<h2> Reverse a string </h2>

In [0]:
def reversestr(phrase):
    
    s = str.split(phrase," ")
    new_p =""
    print(s)
    for i in reversed(range(len(s))):
        
        if s[i]!="" and i != 0:
            new_p+=s[i]+ " "
        else:
            new_p+=s[i]
        
    return new_p.strip()    

In [0]:
reversestr(" hello world ")

['', 'hello', 'world', '']


'world hello'

<h2> Column Excel sheet </h2>

In [0]:
import string

def getcolumn(num):
    
    alphabet = list(string.ascii_lowercase)
    column=""
    test_list = []
    
    if num <= 26:
        
        return alphabet[num-1]
    
    else:
      
        d = num//26
        r = num % 26
        
        return alphabet[d-1] + alphabet[r-1]
       

In [0]:
800//26

30

In [0]:
getcolumn(701)

'zy'

In [0]:
import string

list(string.ascii_lowercase)

<h2> Remove Parenthesis </h2>

In [0]:
def removepar(par):
    
    c_open = 0
    c_close = 0
    pos_op = []
    pos_cl = []
    list_poss = []
    
    for i in range(len(par)):
        
        if par[i] == "(":
            c_open+=1
            pos_op.append(i)
            
        else:
            
            c_close+=1
            pos_cl.append(i)
            
    if c_open > c_close :
        
        for j in range(len(pos_op)):
            
            if pos_op[j]!=0:
                
                list_poss.append(par[:pos_op[j]]+par[pos_op[j]+1:])
                            
        return list(set(list_poss))
    
    elif  c_close > c_open :  
        
        for j in range(len(pos_cl)):
            
            if pos_cl[j]!=len(par)-1:
                
                list_poss.append(par[:pos_cl[j]]+par[pos_cl[j]+1:]) 
                
        return list(set(list_poss))
    
    else :
        
        return par
    


In [0]:
removepar("(()()()")

['(()())', '()()()', '(())()']

<h2> Median of two sorted arrays </h2>

<h3> Sol 1 </h3>

In [0]:
def median(arr1,arr2):
    
    new_tab = np.zeros(arr1.shape[0]+arr2.shape[0])
    
    new_tab = np.hstack([arr1,arr2])
    
    size = new_tab.shape[0]
    
    for i in range(new_tab.shape[0]):
        
        if i < new_tab.shape[0]-2:
        
            j=i+1

            if new_tab[i]>new_tab[j]:

                new_tab[i],new_tab[j]= new_tab[j],new_tab[i]
    
    for i in reversed(range(new_tab.shape[0])):
        
        if i>=1:
        
            j=i-1

            if new_tab[i] < new_tab[j]:

                new_tab[i],new_tab[j]= new_tab[j],new_tab[i]

     
    if new_tab.shape[0] % 2 == 0:
        
        half = int((size/2)-1)
        median = (new_tab[half] + new_tab[half+1]) / 2
        
    else:
        
        median = new_tab[round(size/2)]
    
    
    return median

In [0]:
arr1 = np.array([2,3,5])
arr2 = np.array([1,4,8])

In [0]:
median(arr1,arr2)

3.5

<h3> Sol 2 </h3>

In [0]:
def median2(arr1,arr2):
    
    
    
    
    
    
    return median

<h2> Roman to decimal </h2>

In [0]:
roman=list([["I","V","X","L","C","D","M"],[1,5,10,50,100,500,1000]])

In [0]:
dict_roman = dict(zip(roman[0],roman[1]))

In [0]:
def roman_to_dec(num_r,dict_roman):
    
    sum = 0
    letter=0
    
    while letter < len(num_r):
        
        if len(num_r)==1:
            return dict_roman[num_r[letter]]
            
        elif dict_roman[num_r[letter]] < dict_roman[num_r[letter+1]] and letter < len(num_r)-1:
            sum = (dict_roman[num_r[letter+1]] - dict_roman[num_r[letter]]) + sum
            letter +=2
            
    
        else:
            
            sum = dict_roman[num_r[letter]] + sum
            letter +=1
        
    return sum

In [0]:
roman_to_dec("XM",dict_roman)

990

<h2> Pascal Triangle </h2>

In [0]:
def triangle(iteration):
    
    pascal = []
    
    for i in range(1,iteration+1):
        
        tab = np.ones(i)
        
        if i > 2:
           
            temp = pascal[i-2]
            
            for j in range(1,tab.shape[0]-1):
                
                tab[j] = temp[j-1] + temp[j]
                
            pascal.append(tab)
            
        else:
            
            pascal.append(tab)
            
    
    return pascal

In [0]:
triangle(10)

[array([1.]),
 array([1., 1.]),
 array([1., 2., 1.]),
 array([1., 3., 3., 1.]),
 array([1., 4., 6., 4., 1.]),
 array([ 1.,  5., 10., 10.,  5.,  1.]),
 array([ 1.,  6., 15., 20., 15.,  6.,  1.]),
 array([ 1.,  7., 21., 35., 35., 21.,  7.,  1.]),
 array([ 1.,  8., 28., 56., 70., 56., 28.,  8.,  1.]),
 array([  1.,   9.,  36.,  84., 126., 126.,  84.,  36.,   9.,   1.])]

<h2> Searching values </h2>

<h3> Brute force </h3>

In [0]:
def force_search(arr, search_v):
    
    for i in range(arr.shape[0]):
        
        if arr[i]==search_v:
            
            return print("value found at the index",i)
            break
   
    return print("value not existent")

In [0]:
test = np.array([1,4,5,7,9,10,13])

In [0]:
test[2:6]

array([ 5,  7,  9, 10])

In [0]:
force_search(test,13)

value found at the index 6


<h3> Binary search </h3>

In [0]:
def binary_search(arr,search_v):
    
        size = arr.shape[0]
        
        while size > 1:
            
            if search_v == arr[0]:
                return 0
                break
                
            elif search_v == arr[size-1]:
                return size-1
                break
            
            else:
            
                if arr.shape[0]%2==0:

                    if search_v == arr[(size/2)-1]:
                        return (size/2)-1
                        break

                    elif search_v > arr[(size/2)-1]:
                        arr = arr[(size/2):]
                        size = arr.shape[0]

                    else:
                        arr = arr[:(size/2)]
                        size = arr.shape[0]

                else:

                    if search_v == arr[int(size/2)]:
                        return int(size/2)
                        break

                    elif search_v > arr[int(size/2)]:
                        arr = arr[int(size/2)+1:]
                        size = arr.shape[0]

                    else:
                        arr = arr[:int(size/2)]
                        size = arr.shape[0]
                        
                        
        return print("not existent")

In [0]:
binary_search(test,10)

1

<h3> Recursive binary search </h3>

In [0]:
def rec_binary(arr, search):
    
    size=arr.shape[0]
    
    if size > 1 :
        
        if arr[0] == search or arr[size-1] == search :
            return print("found value")

        elif arr[int(size/2)-1] == search :
            return print("found value")

        elif arr[int(size/2)-1] > search:

            rec_binary(arr[:int(size/2)],search)


        elif arr[int(size/2)-1] < search:

            rec_binary(arr[int(size/2):],search)


    else:

        return print("not found")

In [0]:
rec_binary(test,13)

found value


<h2> Arbres de decisions </h2>

In [0]:
class Binary_Tree():
    
    def __init__(self,key):
        self.key = key
        self.LeftChild = None
        self.RightChild=None
        
    def InsertLeft(self,key):
        
        if self.LeftChild==None : 
            self.LeftChild = Binary_Tree(key)
            
        else:
            t = Binary_Tree(key)
            t.LeftChild = self.LeftChild
            self.LeftChild = t
            
            
    def InsertRight(self,key):
        
        if self.RightChild == None:
            self.RightChild= Binary_Tree(key)
            
        else:
            t = Binary_Tree(key)
            t.RightChild = self.RightChild
            self.RightChild = t
        
    
    def getRight(self):
        return self.RightChild
    
    def getLeft(self):
        return self.LeftChild
    
    def setRoot(self,val):
        self.key = val
    
    def getRoot(self):
        return self.key

In [0]:
r=Binary_Tree("a")
r.InsertLeft("b")
r.getLeft().InsertLeft("g")
r.InsertRight("c")
r.getRight().InsertRight("d")
r.getRight().getRight().InsertLeft("f")
r.getRight().InsertLeft("e")

In [0]:
print(r.getRoot())
print(r.getRight().getRoot())
print(r.getRight().getRight().getRoot())

a
c
d


<h2> Max depth </h2>

In [0]:
def preorder(root):
        
        if root:
             
            ldepth = preorder(root.getLeft())
            rdepth = preorder(root.getRight())
            
            # Use the larger one 
            if (ldepth > rdepth): 
                return ldepth+1
            else: 
                return rdepth+1
            
        else: 
            
            return 0

     


In [0]:
preorder(r)

4

In [0]:
def max_depth(root, depth=1):
    
    if not root:
        return 0
    
    elif not root.getLeft() and not root.getRight():
        return depth
    
    elif not root.getLeft() and root.getRight():
        return max_depth(root.getRight(),depth+1)
        
    
    elif root.getLeft() and not root.getRight():
        return max_depth(root.getLeft(),depth+1)
        
    else:
        return max(max_depth(root.getLeft(),depth+1),max_depth(root.getRight(),depth+1))

In [0]:
max_depth(r)

4

<h2> Traversal order tree </h2>


In [0]:
def add_nodes(root,order,num=0):
    
    if root:
        if num ==0:
            order.append([root.getRoot()])
        
        if root.getLeft() and root.getRight():
            order.append([root.getLeft().getRoot(),root.getRight().getRoot()])
        
        elif root.getLeft():
            order.append([root.getLeft().getRoot()])
            
        elif root.getRight():
            order.append([root.getRight().getRoot()])
        
        num=num+1
        
        add_nodes(root.getRight(),order,num)
        add_nodes(root.getLeft(),order,num)
    
        return order

In [0]:
test = add_nodes(r, [])

In [0]:
test

[['a'], ['b', 'c'], ['e', 'd'], ['f'], ['g']]

<h2> Parcours en largeur de l'arbre </h2>

In [0]:
def bfs(root):
    
    queue = Queue()
    queue.enqueue(root)
    
    while not queue.isEmpty():
        
        v = queue.dequeue()
        print(v.getRoot())
        
        if v.getLeft() and v.getRight():
            queue.enqueue(v.getLeft())
            queue.enqueue(v.getRight())
            
        elif v.getLeft():
            queue.enqueue(v.getLeft())
        
        elif v.getRight():
            queue.enqueue(v.getLeft())

    

In [0]:
bfs(r)

a
b
c
g
e
d
f


<h2> Parcours en profondeur </h2>

In [0]:
def dfs(root):
    
    stack = Stack()
    stack.push(root)
    
    while not stack.isEmpty():
        
        v=stack.pop()
        print(v.getRoot())
        
        if v.getLeft() and v.getRight():
            stack.push(v.getRight())
            stack.push(v.getLeft())
            
        elif v.getLeft():
            stack.push(v.getLeft())
        
        elif v.getRight():
            stack.push(v.getLeft())
        
        

In [0]:
dfs(r)

a
b
g
c
e
d
f


<h2> Power function </h2>

In [0]:
def power(x,n):
     
    
    if n==0:
        return 1
    
    if n>0 :
        powa = x
        for i in range(1,n):
            x *= powa
                
        return x
    
    else:
        powa= x
        for i in range(1,-n):
            x*=powa
            
        return 1 / x
        
    
    

In [0]:
power(9,2)

81

<h2> Multiply two strings </h2>

In [0]:
def convert_str(s):
    
    result = 0 
    value = {'0':0, '1':1, '2':2, '3':3, '4':4, '5':5, '6':6, '7':7, '8':8, '9':9}
    for l in s :
        if l in "0123456789":
            result = result * 10 + value[l]
    return result 


def multuply(str1,str2):
    return convert_str(str1)*convert_str(str2)

In [0]:
multuply("2","120")

240

<h2> Longest word in dictionnary </h2>

In [0]:
def longest(s,dic):
      
    final = ""    
        
    for k in dic :
        
        temp = ""
        v = dic[k]
        
        for letter in range(len(v)):
            
            pos = -1
            
            if v[letter] in s and letter > pos :
                
                temp += v[letter]
                
                pos = letter
                
                if temp == v and len(temp) > len(final) :
                    
                    final = temp    
    
    
    return final

In [0]:
dicto = {0:"apple", 1:"ale", 2:"monkey", 3:"prout"}

In [0]:
longest("mabpconkpleaey",dicto)

'monkey'

<h2> contains duplicate </h2>

<h3> n2 complexity </h3>

In [0]:
def detect_dup(arr,k):
    
    prout = False

    for i in range(arr.shape[0]-1):
        
        limit = i + 1
        
        for j in range(limit, arr.shape[0]):
            
            if arr[i]==arr[j] and abs(i-j)==k:
                
                prout = True 
                return prout
                break  
    
    return prout

In [0]:
val = np.array([1,2,3,2,5,6])

In [0]:
detect_dup(val,2)

False

<h3> n complexity </h3>

In [0]:
def dup_n(arr):
    
    hash = {0:arr[0]}
    
    for i in range(1,arr.shape[0]):
        
        if arr[i] not in hash.values():
            
            hash[i] = arr[i]
            
        else :
            
            print(arr[i],"is a duplicate value")
        
        

In [0]:
dup_n(val)

2 is a duplicate value


<h2> substr implementation <h2>

In [0]:
def substr(big,small):
    
    k=0
    
    for i in range(len(big)):
                        
        if k<=len(small)-1 and big[i]==small[k] :
            k+=1
                           
        else :
            k=0
            
        if k==len(small):
            return i - (k-1)
            break  
    
    
    return -1

In [0]:
substr("bonjourom","on")

1

<h2> Reverse stars Pyramide </h2> 

In [0]:
def reverse_star(n_stars):
    stars = list("*" * n_stars)
    head, queue = 0,len(stars)-1
    while head < queue :
        print("".join(stars))
        stars[head],stars[queue] = " "," "
        head+=1
        queue-=1


In [0]:
reverse_star(30)

******************************
 **************************** 
  **************************  
   ************************   
    **********************    
     ********************     
      ******************      
       ****************       
        **************        
         ************         
          **********          
           ********           
            ******            
             ****             
              **              


<h3> Ideal numbers </h3>

In [0]:
def ideal_num(bot_v, top_v):
    counter = 0
    for i in range(20):
        for j in range(20) :
            if pow(3,i)*pow(5,j) >= bot_v and pow(3,i)*pow(5,j) <= top_v :
                counter +=1
    return counter


In [0]:
ideal_num(1,50)

8

<h2> Test dico </h2>

In [0]:
test = {0: "allo",1:"chien", 2: "bonjour"}

for k,v in test.items():
    print(k,v)

In [0]:
prout = dict((v,k) for k,v in test.items())

In [0]:
prout2 = dict(zip(test.values(),test.keys()))